From 968052d137cd36c2dcc1127cf24d56f877dd35c6 Mon Sep 17 00:00:00 2001
From: Petr Vobornik <pvoborni@redhat.com>
Date: Thu, 26 Feb 2015 19:39:14 +0100
Subject: [PATCH] Return proper error if autodiscovery fails on AD server

https://bugzilla.redhat.com/show_bug.cgi?id=1132261
---
 ipapython/ipautil.py | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/ipapython/ipautil.py b/ipapython/ipautil.py
index e3b724a1af490b5763f9a01a8e9fbff7273dbd97..8fcc3ee3be0c1d6f2f0d596a512130ece9f277a5 100644
--- a/ipapython/ipautil.py
+++ b/ipapython/ipautil.py
@@ -814,7 +814,10 @@ def get_ipa_basedn(conn):
         '', scope=ldap.SCOPE_BASE, attrlist=['defaultnamingcontext', 'namingcontexts']
     )
 
-    contexts = entries[0][1]['namingcontexts']
+    contexts = entries[0][1].get('namingcontexts')
+    if not contexts:
+        root_logger.debug("No naming context found")
+        return None
     if entries[0][1].get('defaultnamingcontext'):
         # If there is a defaultNamingContext examine that one first
         default = entries[0][1]['defaultnamingcontext'][0]
-- 
2.4.3

